spring:

  application:
    name: ingester

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    email-processing:
      exchange: ${RABBITMQ_EXCHANGE}
      queue: ${RABBITMQ_QUEUE}
      routing-key: ${RABBITMQ_ROUTING_KEY}






resilience4j:
  retry:
    instances:
      gmailRetry:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        randomized-wait-factor: 0.5
        retry-exceptions:
          - com.inboxintelligence.ingester.exception.RetryableGmailApiException

gmail-api:
  application-name: "InboxIntelligence"
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${GOOGLE_REDIRECT_URI}
  token-url: "https://oauth2.googleapis.com/token"
  scope: "openid email https://www.googleapis.com/auth/gmail.readonly"
  pubsub-topic: ${GCP_PUBSUB_TOPIC}
  project-id: ${GCP_PROJECT_ID}
  pubsub-subscription-id: ${GCP_PUBSUB_SUBSCRIPTION_ID}
  service-account-key-path: ${GCP_SERVICE_ACCOUNT_KEY_PATH:./gcp-service-account.json}

email-storage:
  provider: ${EMAIL_STORAGE_PROVIDER}
  local-base-path: ${EMAIL_STORAGE_LOCAL_BASE_PATH}
