spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    email-processing:
      exchange: test
      queue: test
      routing-key: test

gmail-api:
  client-id: test
  client-secret: test
  redirect-uri: http://localhost
  scope: test
  pubsub-topic: test
  project-id: test
  pubsub-subscription-id: test
  service-account-key-path: ./gcp-service-account.json

email-storage:
  provider: LOCAL
  local-base-path: /tmp/ingester-test
